// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCul2qnlDvxb9Luehbn-9DNfhuC_U-2VXQ',
    appId: '1:532792780458:web:10828c5780e60697e9d2d3',
    messagingSenderId: '532792780458',
    projectId: 'dataupload-dfc27',
    authDomain: 'dataupload-dfc27.firebaseapp.com',
    storageBucket: 'dataupload-dfc27.appspot.com',
    measurementId: 'G-GGVRJ17BDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO1hDoiPEXVDElSQsvvmTaXC17JNkObAc',
    appId: '1:532792780458:android:12ee975bdc9d2c64e9d2d3',
    messagingSenderId: '532792780458',
    projectId: 'dataupload-dfc27',
    storageBucket: 'dataupload-dfc27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1-MUF24CHygYiCtLAQ6OdcVuSfh-AcHE',
    appId: '1:532792780458:ios:4b5e9bee8f491ffde9d2d3',
    messagingSenderId: '532792780458',
    projectId: 'dataupload-dfc27',
    storageBucket: 'dataupload-dfc27.appspot.com',
    iosBundleId: 'com.example.dataUpload',
  );
}
